media-user-token: ''
authorization-token: ''
language: ''
lrc-type: lyrics
lrc-format: lrc
embed-lrc: true
save-lrc-file: false
save-artist-cover: false
save-animated-artwork: false
emby-animated-artwork: false
embed-cover: true
cover-size: 5000x5000
cover-format: jpg
alac-save-folder: ALAC Downloads
atmos-save-folder: Atmos Downloads
aac-save-folder: AAC Downloads
mv-save-folder: Music Video Downloads
max-memory-limit: 256
decrypt-m3u8-port: 127.0.0.1:10020
get-m3u8-port: 127.0.0.1:20020
get-m3u8-from-device: true
get-m3u8-mode: hires
aac-type: aac-lc
alac-max: 192000
atmos-max: 2768
limit-max: 200
album-folder-format: '{AlbumName} [{ReleaseYear}]'
playlist-folder-format: '{PlaylistName}'
song-file-format: '{DiscNumber}-{SongNumber}. {SongName}'
artist-folder-format: '{UrlArtistName}'
explicit-choice: '[E]'
clean-choice: '[C]'
apple-master-choice: '[M]'
use-songinfo-for-playlist: true
dl-albumcover-for-playlist: true
use-song-metadata-for-playlist-numbering: false
mv-audio-type: atmos
mv-max: 2160
storefront: ''
preferred-quality: AAC
mv-file-format: '{ArtistName} - {VideoName} [{ReleaseYear}]'
